### ISSUE TITLE
Your teleG is compromised. I won't use it anymore. 

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [mpolinowski/mpolinowski.github.io#1]
Received strange info, I don't think it's you.

**Comment by mpolinowski** [comment]
I tried contacting you this morning. You closed the conversation?

**Comment by AnnieTaylorCHEN** [comment]
yeah...it looks suspicious so I removed the app.

*Annie Taylor CHEN*
Full-stack developer | stylist | photographer | cook
Portfolio: https://www.annietaylorchen.com/
