### ISSUE TITLE
RE MQTT Cheat sheet; Missing info about DUP flag 

### ISSUE THREAD

**Issue by a-l-e-c** [mpolinowski/mpolinowski.github.io#1]
Found your cheat sheet (very helpful btw, thanks!) and saw you had a `?` for the `Description` of the Publish Parameter `d0 / d1`

Turns out it's the `DUP flag` used to indicate if a message was resent.

_FYI: I was unable to find any documentation regarding the DUP flag/bit in the official Mosquitto documentation._

Path to your doc: `docs/Development/Javascript/2021-06-02--mqtt-cheat-sheet/2021-06-02/index.html`

Spec link: [DUP flag](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901102)

**Comment by mpolinowski** [comment]
Hey Alec,

> (very helpful btw, thanks!)

Glad it was useful ☺️ 

I did not have enough time to play with version 5, yet. Thank you for pointing me to this article. I added the link + description to the note 👍🏻 

https://mpolinowski.github.io/docs/Development/Javascript/2021-06-02--mqtt-cheat-sheet/2021-06-02#debugging

**Comment by a-l-e-c** [comment]
Awesome, thanks again!
